learning_rate: 1e-3  # 2e-3  # 1e-3  # 5e-4  # 3e-4
reduce_lr_on_plateau_factor: 0.5  # Set to 0.0 to disable
reduce_lr_on_plateau_patience: 500
reduce_lr_on_plateau_min_learning_rate: 1e-6
reduce_lr_on_plateau_monitor: "val_loss"