_target_: networks.baseline.CurrentValueBaseline
label_index: 0  # Column index in `train_df` containing the labels


# To find label_index, run:
# column_indices = {name: i for i, name in enumerate(train_df.columns)}
# label_column = cfg.data.labels_columns[0]
# label_index = column_indices[label_column]
