_target_: networks.recurrent.GRUNetwork
rnn_units: [256]  # [64, 64, 64]  # Be careful of u > window_size
hidden_dense_layers: [64, 16]  # [128]
dropout_rate_rnn: 0.0
dropout_rate_dense: 0.0
use_batchnorm: False
num_outputs: 1  # Must match config_data["window_label_width"].
