defaults:
  - _self_
  - loss: huber
  - model: dense_mlp
  - dataset_generator: linear
  - data: processed  # [processed, processed_lagged]
  - optimisation: reduce_lr_on_plateau
  - logging: wandb

use_full_data: False

train:
  epochs: 250
  batch_size: 32
  validation_ratio: 0.11  # 0.3. # 0.11 --> 1 year
